### ISSUE TITLE
it is hurry,thanks

### ISSUE THREAD

**Issue by ReverseSystem001** [snavely/bundler_sfm#47]
when i run bundler on other downloaded public pictures.there comes the questions you tell in Frequently asked Questions (FAQ) about Bundler .
then i followed the steps you told. before the last step: Then rerun bundler (just bundler, and not the matching or other steps) ---my matches.init.txt file is empty.is it all right?? and when i copyed the code:bundler list.txt --options_file options.txt .it does not run . what should i write?
can you help me ??

**Comment by snavely** [comment]
Hi,

Did my answer to your other question address this issue as well?

Noah

On Mar 3, 2017 6:56 AM, "ReverseSystem001" <notifications@github.com> wrote:

when i run bundler on other downloaded public pictures.there comes the
questions you tell in Frequently asked Questions (FAQ) about Bundler .
then i followed the steps you told. before the last step: Then rerun
bundler (just bundler, and not the matching or other steps) ---my
matches.init.txt file is empty.is it all right?? and when i copyed the
code:bundler list.txt --options_file options.txt .it does not run . what
should i write?
can you help me ??

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/snavely/bundler_sfm/issues/47>, or mute the thread
